[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
via_ir = true
solc = '0.8.28'
optimizer-runs = 200

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
bsc = "${BSC_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
aurora = "${AURORA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
base = "${BASE_RPC_URL}"
linea = "${LINEA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHEREUM_BLOCKSCAN_KEY}" }
arbitrum = { key = "${ARBITRUM_BLOCKSCAN_KEY}" }
optimism = { key = "${OPTIMISM_BLOCKSCAN_KEY}" }
polygon = { key = "${POLYGON_BLOCKSCAN_KEY}" }
bsc = { key = "${BSC_BLOCKSCAN_KEY}" }
gnosis = { key = "${GNOSIS_BLOCKSCAN_KEY}" }
avalanche = { key = "${AVALANCHE_BLOCKSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
